// OpencodePlugin.swift -- the opencode integration, which is one generated JS file.
//
// opencode has no settings.json hooks: plugins are ES modules loaded from its config
// directory, so installing is writing this file and detecting is finding the marker on
// its first line. The marker is also what lets a user's own file at the same path be
// left alone by remove.

import Foundation

enum OpencodePlugin {
    static let marker =
        "// cuelight plugin -- generated by cuelight; edits will be overwritten."

    /// The plugin lives under the home root, like every agent config.
    static func url(home: URL) -> URL {
        home.appendingPathComponent(".config/opencode/plugins", isDirectory: true)
            .appendingPathComponent("cuelight.js")
    }

    static func isOurs(at url: URL) -> Bool {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return false }
        return text.contains(marker)
    }

    static func install(into home: URL, executable: String) throws {
        let url = url(home: home)
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(),
                                                withIntermediateDirectories: true)
        try template(executable: executable).write(to: url, atomically: true, encoding: .utf8)
    }

    /// Deletes only a file carrying the marker: a foreign file with the same name is
    /// not ours to delete, even if it occupies the path we would have written.
    static func remove(from home: URL) {
        let url = url(home: home)
        guard isOurs(at: url) else { return }
        try? FileManager.default.removeItem(at: url)
    }

    /// The generated ES module: the shared helpers and the V1 hooks object, with the
    /// V2 entrypoint appended. opencode 1 loads the named export (a plugin input
    /// returning a hooks object); opencode 2 loads the default export's `setup` and
    /// calls `server` only for the V1 loader, so one file serves both.
    static func template(executable: String) -> String {
        """
        \(marker)
        //
        // Forward the events the lamp cares about to `cuelight hook opencode <event>`.
        // Every error is swallowed: a broken lamp must never break opencode.

        import { spawn } from "node:child_process";

        const EXECUTABLE = \(jsString(executable));
        const FORWARDED = new Set([
          "session.idle",
          "permission.asked",
          "permission.replied",
          "question.asked",
          "question.replied",
          "question.rejected",
          "session.deleted",
        ]);

        // Fire-and-forget: the child gets its payload on stdin and is then detached and
        // unref'd, so a slow or missing cuelight never delays opencode. Registering
        // "event" and filtering here is deliberate -- forwarding every streaming update
        // would spawn a process per token.
        function forward(rawEvent, payload) {
          try {
            const child = spawn(EXECUTABLE, ["hook", "opencode", rawEvent], {
              stdio: ["pipe", "ignore", "ignore"],
              detached: true,
            });
            child.on("error", () => {});
            child.stdin.on("error", () => {});
            child.stdin.end(JSON.stringify(payload));
            child.unref();
          } catch {
            // never break opencode
          }
        }

        export const CuelightPlugin = async ({ directory, worktree }) => {
          // Subagent sessions must not blink the lamp for the main agent, the same rule
          // Claude's missing SubagentStop hook enforces. Their ids are tracked here.
          const childSessions = new Set();

          const send = (rawEvent, sessionID) => {
            if (!sessionID || childSessions.has(sessionID)) return;
            forward(rawEvent, {
              session_id: sessionID,
              cwd: directory ?? worktree ?? process.cwd(),
              pid: process.pid,
            });
          };

          return {
            "chat.message": async ({ sessionID }) => {
              send("chat.message", sessionID);
            },

            event: async ({ event }) => {
              try {
                const type = event?.type;
                const properties = event?.properties ?? {};
                const info = properties.info;
                if (type === "session.created" && info?.id && info?.parentID) {
                  childSessions.add(info.id);
                  return;
                }
                const sessionID = properties.sessionID ?? info?.id ?? "";
                if (childSessions.has(sessionID)) {
                  if (type === "session.deleted") childSessions.delete(sessionID);
                  return;
                }
                if (FORWARDED.has(type)) send(type, sessionID);
              } catch {
                // never break opencode
              }
            },
          };
        };
        """
        + v2Entrypoint
    }

    /// opencode 2 (2.0+) loads a default export with an id and a setup function
    /// instead of the V1 hooks object, and hands event payloads over as `data`
    /// rather than `properties`. The V1 shape above stays as `server`, so one file
    /// serves both loaders.
    ///
    /// V2 loads one instance per location and every instance sees the whole server's
    /// event stream. Only the instance that owns a session's location forwards it,
    /// so the lamp hears one voice per event.
    private static let v2Entrypoint = """
        // opencode 2 loads a default export with an id and a setup function; the V1
        // hooks object above stays as `server`, so one file serves both loaders.
        export default {
          id: "cuelight.opencode",
          server: CuelightPlugin,
          setup(ctx) {
            const here = ctx.location?.directory ?? "";
            const childSessions = new Set();
            const sessionLocations = new Map();
            const controller = new AbortController();

            const send = (rawEvent, sessionID, cwd) => {
              if (!sessionID || childSessions.has(sessionID)) return;
              forward(rawEvent, {
                session_id: sessionID,
                cwd: cwd || here || process.cwd(),
                pid: process.pid,
              });
            };

            // V2 renamed some of the events: questions became forms, and a finished
            // turn is an execution. Forward the names the lamp already knows.
            const RENAMED = new Map([
              ["session.execution.succeeded", "session.idle"],
              ["session.execution.interrupted", "session.idle"],
              ["permission.rejected", "permission.replied"],
              ["form.created", "question.asked"],
              ["form.replied", "question.replied"],
              ["form.cancelled", "question.rejected"],
            ]);

            const owns = (sessionID, location) => {
              const directory = location?.directory;
              if (directory) sessionLocations.set(sessionID, directory);
              const known = sessionLocations.get(sessionID);
              if (known !== undefined) return known === here;
              // A session created before this instance loaded has no location yet.
              // Ask the server, and let this one event through rather than lose it.
              void ctx.session.get({ sessionID }).then((info) => {
                const dir = info?.location?.directory;
                if (dir) sessionLocations.set(sessionID, dir);
              }).catch(() => {});
              return true;
            };

            void ctx.session.hook("prompt", (event) => {
              try {
                if (owns(event?.sessionID)) send("chat.message", event?.sessionID, here);
              } catch {
                // never break opencode
              }
            });

            void (async () => {
              for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
                try {
                  const type = event?.type;
                  const data = event?.data ?? {};
                  if (type === "session.created") {
                    if (data.sessionID && data.parentID) childSessions.add(data.sessionID);
                    continue;
                  }
                  const sessionID = data.sessionID ?? data.form?.sessionID ?? "";
                  if (childSessions.has(sessionID)) {
                    if (type === "session.deleted") childSessions.delete(sessionID);
                    continue;
                  }
                  if (FORWARDED.has(type) || RENAMED.has(type)) {
                    if (owns(sessionID, event?.location)) {
                      send(RENAMED.get(type) ?? type, sessionID, event?.location?.directory);
                    }
                    if (type === "session.deleted") sessionLocations.delete(sessionID);
                  }
                } catch {
                  // never break opencode
                }
              }
            })();

            return () => controller.abort();
          },
        };
        """

    /// A JSON string literal is also a valid JS string literal, and it survives paths
    /// with quotes or backslashes that plain interpolation would corrupt. Forward
    /// slashes are left alone: JSONSerialization escapes them by default, which would
    /// write an ugly `\/Users\/...` into a file a person may open.
    private static func jsString(_ text: String) -> String {
        if let data = try? JSONSerialization.data(
            withJSONObject: text,
            options: [.fragmentsAllowed, .withoutEscapingSlashes]),
           let literal = String(data: data, encoding: .utf8) {
            return literal
        }
        let escaped = text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
