// OpencodePlugin.swift -- the opencode integration, which is one generated JS file.
//
// opencode has no settings.json hooks: plugins are ES modules loaded from its config
// directory, so installing is writing this file and detecting is finding the marker on
// its first line. The marker is also what lets a user's own file at the same path be
// left alone by remove.

import Foundation

enum OpencodePlugin {
    static let marker =
        "// cuelight plugin -- generated by cuelight; edits will be overwritten."

    /// The plugin lives under the home root, like every agent config.
    static func url(home: URL) -> URL {
        home.appendingPathComponent(".config/opencode/plugins", isDirectory: true)
            .appendingPathComponent("cuelight.js")
    }

    static func isOurs(at url: URL) -> Bool {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return false }
        return text.contains(marker)
    }

    static func install(into home: URL, executable: String) throws {
        let url = url(home: home)
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(),
                                                withIntermediateDirectories: true)
        try template(executable: executable).write(to: url, atomically: true, encoding: .utf8)
    }

    /// Deletes only a file carrying the marker: a foreign file with the same name is
    /// not ours to delete, even if it occupies the path we would have written.
    static func remove(from home: URL) {
        let url = url(home: home)
        guard isOurs(at: url) else { return }
        try? FileManager.default.removeItem(at: url)
    }

    /// The generated ES module, shaped like the plugins opencode already loads (a
    /// named export taking the plugin input and returning a hooks object).
    static func template(executable: String) -> String {
        """
        \(marker)
        //
        // Forward the events the lamp cares about to `cuelight hook opencode <event>`.
        // Every error is swallowed: a broken lamp must never break opencode.

        import { spawn } from "node:child_process";

        const EXECUTABLE = \(jsString(executable));
        const FORWARDED = new Set([
          "session.idle",
          "permission.asked",
          "permission.replied",
          "question.asked",
          "question.replied",
          "question.rejected",
          "session.deleted",
        ]);

        // Fire-and-forget: the child gets its payload on stdin and is then detached and
        // unref'd, so a slow or missing cuelight never delays opencode. Registering
        // "event" and filtering here is deliberate -- forwarding every streaming update
        // would spawn a process per token.
        function forward(rawEvent, payload) {
          try {
            const child = spawn(EXECUTABLE, ["hook", "opencode", rawEvent], {
              stdio: ["pipe", "ignore", "ignore"],
              detached: true,
            });
            child.on("error", () => {});
            child.stdin.on("error", () => {});
            child.stdin.end(JSON.stringify(payload));
            child.unref();
          } catch {
            // never break opencode
          }
        }

        export const CuelightPlugin = async ({ directory, worktree }) => {
          // Subagent sessions must not blink the lamp for the main agent, the same rule
          // Claude's missing SubagentStop hook enforces. Their ids are tracked here.
          const childSessions = new Set();

          const send = (rawEvent, sessionID) => {
            if (!sessionID || childSessions.has(sessionID)) return;
            forward(rawEvent, {
              session_id: sessionID,
              cwd: directory ?? worktree ?? process.cwd(),
              pid: process.pid,
            });
          };

          return {
            "chat.message": async ({ sessionID }) => {
              send("chat.message", sessionID);
            },

            event: async ({ event }) => {
              try {
                const type = event?.type;
                const properties = event?.properties ?? {};
                const info = properties.info;
                if (type === "session.created" && info?.id && info?.parentID) {
                  childSessions.add(info.id);
                  return;
                }
                const sessionID = properties.sessionID ?? info?.id ?? "";
                if (childSessions.has(sessionID)) {
                  if (type === "session.deleted") childSessions.delete(sessionID);
                  return;
                }
                if (FORWARDED.has(type)) send(type, sessionID);
              } catch {
                // never break opencode
              }
            },
          };
        };
        """
    }

    /// A JSON string literal is also a valid JS string literal, and it survives paths
    /// with quotes or backslashes that plain interpolation would corrupt. Forward
    /// slashes are left alone: JSONSerialization escapes them by default, which would
    /// write an ugly `\/Users\/...` into a file a person may open.
    private static func jsString(_ text: String) -> String {
        if let data = try? JSONSerialization.data(
            withJSONObject: text,
            options: [.fragmentsAllowed, .withoutEscapingSlashes]),
           let literal = String(data: data, encoding: .utf8) {
            return literal
        }
        let escaped = text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
